### ISSUE TITLE
nolining class being added to all browsers not just IE

### ISSUE THREAD

**Issue by devonmather** [zmmbreeze/lining.js#10]
It appears the .nolining class is being added to the html element on all browsers not just browsers that have no support like IE.

http://zencode.in/lining.js/ tested in Chrome, Safari and Firefox.

Maybe i've misunderstood something but at present its making IE fallbacks tricky.

Regards.
Devon Mather

**Comment by zmmbreeze** [comment]
I have fixed the `nolining` issue.  c21837dc66cee595bc22ebf8543ddfecd2a54878
