### ISSUE TITLE
Conflict with lining.js and Slick slider plugin

### ISSUE THREAD

**Issue by devonmather** [zmmbreeze/lining.js#12]
Hello,

I'm trying to implement this with this jquery plugin http://kenwheeler.github.io/slick/ but having no luck.

I've created an example of the issue here http://codepen.io/anon/pen/qdzqVO

It seems removing the call to initilize the slider on #homeSlider allows lining.js to work. Is there any simple solution to this issue, I'm not seeing any console errors in Chrome console.

Thanks in advance

**Comment by devonmather** [comment]
After further testing, looks like somehow the following css on the parent element was causing it to not work, not sure why; but problem solved for now :)

```
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
```

**Comment by zmmbreeze** [comment]
Good job :+1: 

lining.js need the [selection api](https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify) to calculate the `line`. So if `user-select: none;` then text will be unselectable.
