### ISSUE TITLE
JS engine crash when lining.js is applied to elements with "display: none"

### ISSUE THREAD

**Issue by mremco** [zmmbreeze/lining.js#13]
In my setup, the browser's JS engine seems to be crashing when lining.js is applied to elements with "display: none" to them.

This happens in Safari 9 for Mac and in mobile Safari 8.1. It doesn't matter if auto-resize is used or not.

In Firefox for Mac I've seen an infinite loop happen — not every time though — when resizing the browser pretty fast, even when there are no "display: none" items with lining.js applied.

**Comment by drewdrewthis** [comment]
I wish there was a fix for this. I had to do a height = 0; overflow = hidden; css hack so that the lining wouldn't break my layout. The quick resize thing I can't fix tho

**Comment by zmmbreeze** [comment]
I'm afraid it can be done. lining.js required to calculate the **real line** when element is visible. `height = 0; overflow = hidden;` could work, 👍
