### ISSUE TITLE
Issue when initialising the lining on an empty element

### ISSUE THREAD

**Issue by devonmather** [zmmbreeze/lining.js#9]
Seems to duplicate html unnecessarily, cant quite figure out exactly how it happens.

The use case is an h2 element being filled with caption text based on a current nivo-slide.

Also seems to happen when only one word exists.

**Comment by zmmbreeze** [comment]
Is this still an issue?

**Comment by devonmather** [comment]
Yes, seems to be somewhat related to nivo-slider. I can't quite figure out
what causes it but empty elements seem to do it. In this particular case
when in chrome and you resize the browser down e.g. to 320px wide the text
effect takes place on the button as well as the text with the white
background.

http://demo.qualitybusinesswebsites.com.au/

Regards,
Devon Mather

**Comment by zmmbreeze** [comment]
I found the reason. Because lining.js only support block element(`display:block;`) to make sure it contains at least one line.
And in this demo, when browser down to 320px wide, the `h2` element become `display:inline;`.
